// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Project_No_Country_E48.Data;

#nullable disable

namespace Project_No_Country_E48.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Project_No_Country_E48.Models.LeadInteraction", b =>
                {
                    b.Property<int>("InteractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InteractionId"));

                    b.Property<DateTime>("InteractionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InteractionMetadataJson")
                        .HasColumnType("text");

                    b.Property<int>("InteractionSource")
                        .HasColumnType("integer");

                    b.Property<int>("InteractionType")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("InteractionId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("LeadInteractions");
                });

            modelBuilder.Entity("Project_No_Country_E48.Models.LeadScore", b =>
                {
                    b.Property<int>("LeadScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeadScoreId"));

                    b.Property<int>("LeadScoreClassification")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LeadScoreDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LeadScoreValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ScoreModelVersion")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LeadScoreId");

                    b.HasIndex("UserId");

                    b.ToTable("LeadScores");
                });

            modelBuilder.Entity("Project_No_Country_E48.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<string>("ProductCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ProductPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Project_No_Country_E48.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<decimal>("UserBudget")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("UserCity")
                        .HasColumnType("text");

                    b.Property<DateTime>("UserCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserEmail")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserType")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Project_No_Country_E48.Models.LeadInteraction", b =>
                {
                    b.HasOne("Project_No_Country_E48.Models.Product", "Product")
                        .WithMany("LeadInteractions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project_No_Country_E48.Models.User", "User")
                        .WithMany("LeadInteractions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project_No_Country_E48.Models.LeadScore", b =>
                {
                    b.HasOne("Project_No_Country_E48.Models.User", "User")
                        .WithMany("LeadScores")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project_No_Country_E48.Models.Product", b =>
                {
                    b.Navigation("LeadInteractions");
                });

            modelBuilder.Entity("Project_No_Country_E48.Models.User", b =>
                {
                    b.Navigation("LeadInteractions");

                    b.Navigation("LeadScores");
                });
#pragma warning restore 612, 618
        }
    }
}
